global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
       - prometheus:9090
  - job_name: nextjs
    static_configs:
    - targets:
       - 172.30.188.4:3000
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']